@startuml package diagram
!theme reddress-lightblue

left to right direction

package "UI" <<folder>> {
   class DisplayManager
   enum Color
}

package "Logic" <<folder>> {
   class Scheduler
   class Shop
   class Menu
   class ItemDisplayEntity
   class ItemData
   class TempWorldEntityUtils
   class Player
}

package "Storage" <<folder>> {
   class StoreManager
   class MenuPresetAndControl
}

UI ..> Logic
Logic ..> UI
Logic ..> Storage
UI ..> Storage

@enduml