@startuml sequence diagram
!theme reddress-lightblue

header 管理员进入编辑模式

actor 玩家 as player
participant "menu:Menu" as Menu
participant MenuPreset <<(C, #d884c3)>>
participant DisplayManager <<(C, #d884c3)>>

activate Menu
player -> Menu : 玩家左键进入编辑模式控件
alt 玩家是管理员
   Menu -> MenuPreset : 获取编辑菜单信息
   activate MenuPreset
   Menu <-- MenuPreset
   deactivate MenuPreset
   Menu -> Menu : menu 更新自身状态
   activate Menu
   deactivate Menu
   Menu -> DisplayManager : 更新物品展示实体
   activate DisplayManager
   Menu <-- DisplayManager
   deactivate DisplayManager
else
   player <- Menu : 通知玩家没有权限
end

@enduml