@startuml sequence diagram
!theme reddress-lightblue

header 玩家浏览出售商店和购买

actor 玩家 as player
participant "menu:Menu" as Menu
participant StoreManager <<(C, #d884c3)>>
participant DisplayManager <<(C, #d884c3)>>

activate Menu

player -> Menu : 玩家左键被 menu 检测
Menu -> Menu : 获取该物品的 id
activate Menu
deactivate Menu
Menu -> StoreManager : 通过 id 获取该物品信息
activate StoreManager
Menu <-- StoreManager
deactivate StoreManager
alt 物品不存在
   Menu -> Menu : menu 更新自身状态
   activate Menu
   deactivate Menu
   Menu -> StoreManager : 重新获取整页物品信息
   activate StoreManager
   Menu <-- StoreManager
   deactivate StoreManager
   Menu -> DisplayManager : 生成物品展示实体
   activate DisplayManager
   Menu <-- DisplayManager
   deactivate DisplayManager
   player <- Menu : 通知玩家物品不存在
else 物品存在
   alt 第一次左键该物品
      Menu -> Menu : menu 更新自身状态
      note right
         出售商店的物品数量无限
         玩家操作后不会产生变化
         应仅在最开始需要两次左键确认
         连续操作同个物品后续无需两次左键确认
      end note
      activate Menu
      deactivate Menu
   else 玩家确认操作
      alt 钱足够
         Menu -> Menu : 扣除玩家金钱
         activate Menu
         deactivate Menu
         Menu -> StoreManager : 写入玩家历史购买
         activate StoreManager
         Menu <-- StoreManager
         deactivate StoreManager
         player <- Menu : ObtainItem()
      else 钱不够
         player <- Menu : 通知玩家钱不够
      end
   end
end

@enduml